name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código com fetch-depth > 1
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Baixar todo o histórico de commits

      # Configuração do PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # Instalação das dependências
      - name: Install dependencies
        run: |
          composer install

      # Execução dos testes PHPUnit e exibição do resultado
      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --coverage-clover=coverage.xml --verbose  # Adicionando --verbose para mostrar o resultado

      # Exibição do arquivo de cobertura
      - name: Display Coverage Results
        run: |
          cat coverage.xml  # Exibe o conteúdo da cobertura gerada (opcional)

      # Envia a cobertura de código para o Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
