name: PHPUnit Tests with Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Ajuste a versão do PHP conforme necessário

      # Instalar dependências
      - name: Install dependencies
        run: |
          composer install

      # Rodar os testes com PHPUnit e gerar o relatório de cobertura
      - name: Run PHPUnit tests with coverage
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml -v

      # Upload do relatório de cobertura para o Codecov (se configurado)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml

      # Verificar a cobertura de código e bloquear o merge se for abaixo de 60%
      - name: Check coverage percentage
        run: |
          COVERAGE=$(bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} | grep 'All Tests' | awk '{print $5}' | tr -d '%')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
            echo "Coverage is below 60%, blocking merge!"
            exit 1
          fi
