name: Run Tests and Check Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # Install dependencies using Composer
      - name: Install dependencies
        run: |
          composer install

      # Disable Xdebug if it's loaded
      - name: Disable Xdebug if enabled
        run: |
          if php -m | grep -q 'xdebug'; then
            echo "Disabling Xdebug"
            php -d xdebug.mode=off -r 'echo "Xdebug disabled\n";'
          fi

      # Run PHPUnit tests with code coverage
      - name: Run PHPUnit tests with code coverage
        run: |
          ./vendor/bin/phpunit --coverage-clover=coverage.xml

      # Upload coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  check-coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Check if Codecov report passes the coverage threshold
      - name: Check code coverage
        run: |
          curl -s https://codecov.io/bash > codecov.sh
          bash codecov.sh -t ${{ secrets.CODECOV_TOKEN }}
          coverage_percentage=$(curl -s https://codecov.io/api/gh/${{ github.repository }}/commits/${{ github.sha }} | jq -r '.commit.total.coverage')
          
          if (( $(echo "$coverage_percentage < 60" | bc -l) )); then
            echo "Code coverage is below 60%. Merge not allowed."
            exit 1
          fi
          echo "Code coverage is above 60%. Proceeding with the merge."
